# Generated by Django 3.1.7 on 2021-09-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='MartialStatus',
            field=models.CharField(max_length=15),
        ),
    ]
