# Generated by Django 3.2.7 on 2021-09-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_auto_20210919_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='Age',
            new_name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='MartialStatus',
        ),
    ]
