# Generated by Django 3.2.7 on 2021-09-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_auto_20210926_1650'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newuser',
            table='App1_newuser',
        ),
    ]
