# Generated by Django 3.2.7 on 2021-09-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_alter_newuser_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Email', models.CharField(max_length=120)),
                ('PhoneNumber', models.IntegerField()),
                ('Gender', models.CharField(max_length=120)),
                ('Prerequisite', models.CharField(max_length=120)),
                ('Education', models.CharField(max_length=120)),
                ('Description', models.CharField(max_length=250)),
            ],
        ),
    ]
