# Generated by Django 3.1.7 on 2021-09-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
                ('pwd', models.CharField(max_length=150)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=1)),
                ('MartialStatus', models.CharField(max_length=1)),
            ],
        ),
    ]
